### PR TITLE
Created home page for the website

### PR DESCRIPTION
**Pull request by glennfor**
The home page for the website is mostly complete in home.html. The follow up pages will come as per the requirements of the back end. 

The file is using a CDN for Jquery, tailwind, AOS.

### CODE REVIEW

**Review by SaahBrice — APPROVED** [review]
Thanks for the update...checking...

**Comment by SaahBrice** [comment]
Excellent UPDATE

A few adjustments we to work on;

1. **The mobile view is not the best.**

- The title "Dedicated to excellence" should auto adjust (by reducing size) and centralized at the bottom when on mobile view.
- Not enough margin in the paragraph e.g in the paragraph of our motto
- reduce navbar buttons to a single button containing other buttons, (don't continuously show buttons as the are)

2. **Theme Generalities**

- reduce the font-size if the titles
- use two colors in this theme, blue and white. 
- all icons in white bg should be in blue and all icons in blue should be in white
- All text in white bg, in black and all text in blue bg in white
- buttons in white bg in blue and in blue bg in white.
- change all font type to "Roboto"
- Hover effects: text change from black to blue in white bg and from white to black in blue bg
- use same kind of icons on footer as on other sections and use same size of icon all through
- Reduce size of chart
- use same kind of cards
3. **Animations**
- use one type of animation for all the entries
- add shadow on cards only when the mouse enters region

**Comment by SaahBrice** [comment]
Excellent UPDATE

A few adjustments we to work on;

1. **The mobile view is not the best.**

- The title "Dedicated to excellence" should auto adjust (by reducing size) and centralized at the bottom when on mobile view.
- Not enough margin in the paragraph e.g in the paragraph of our motto
- reduce navbar buttons to a single button containing other buttons, (don't continuously show buttons as the are)

2. **Theme Generalities**

- reduce the font-size if the titles
- use two colors in this theme, blue and white. 
- all icons in white bg should be in blue and all icons in blue should be in white
- All text in white bg, in black and all text in blue bg in white
- buttons in white bg in blue and in blue bg in white.
- change all font type to "Roboto"
- Hover effects: text change from black to blue in white bg and from white to black in blue bg
- use same kind of icons on footer as on other sections and use same size of icon all through
- Reduce size of chart
- use same kind of cards
3. **Animations**
- use one type of animation for all the entries
- add shadow on cards only when the mouse enters region

**Comment by glennfor** [comment]
Thank you for the feedback. I will make sure to apply it across the site.

I have gone through the website
<http://www.rainbowbilingualschooldschang.org/>trying to find all the
endpoints so I can know how many pages/components will be needed.
As of now, I have found the following actions
*Backend*
get results
apply
register
login
school programs
news [on home page]

*Pure Frontend*
Home page
Page for schools[preschool, primary and secondary]

At this moment I understand I can't go any further because I will need a
structure of the backend in
other to know how to structure the front.

I also have some ideas on the struture: For example on the application
page, there
are multiple forms for each item(form 1, nursery school, form2 to 4 ,...
and so on). I was contemplating if that
could just be implemented as a single form with only the necessary fields
presented as required by the category(nursery, primary, ...).

In all, what I am saying is that, except you have something in mind I will
need like a blueprint of how the
backend for each of those endpoints looks like so I can put in the
necessary components and actually have a definite end goal.

Thanks

**Comment by SaahBrice** [comment]
I understand you.
For the backend, i don't think anything will be changed. But for the
structure of the applications, when you click on any, it takes you to a
dedicated form. Relating to the structure, i am not really sure to
understand what you mean. Are you relating to the form or the page itself,
as to the layout. If it's the form then for the moment it's not proprietary
but if your talking about the page itself then it's open to your
suggestions.
Meanwhile for the moment, all the backend except the results section
accessed from the login is unchanged.

I hope i have answered your questions

**Comment by glennfor** [comment]
Not entirely but it's all right. I have gotten your point. I will work on
the changes and on the additional pages for now.

**Comment by SaahBrice** [comment]
Alright thank you and courage.
I'll be waiting for your requests subsequently

**Pull request merged**
